### ISSUE TITLE
Panics when ran

### ISSUE THREAD

**Issue by sbkg0002** [abdullah-alaadine/local-git-contributions-visualizer#12]
Hey!

Thanks for sharing your work! Any idea why a checkout of today isnt working?
```➜ ./local-git-contributions-visualizer
Enter your Git email address: me@me.com
Enter the folder path to scan for Git repositories: /Users/me/git/github.com/myorg/myrepo
Enter your stats type (1: Table --- 2: Graph): 1
⡿panic: object not found

goroutine 1 [running]:
main.fillCommits({0x140000183c0, 0x1e}, {0x14000462160?, 0x0?}, 0x1400017e120)
	/Users/me/git/github.com/abdullah-alaadine/local-git-contributions-visualizer/stats.go:85 +0x188
main.processRepositories({0x140000183c0, 0x1e})
	/Users/me/git/github.com/abdullah-alaadine/local-git-contributions-visualizer/stats.go:154 +0xdc
main.stats({0x140000183c0?, 0x43?}, 0x1)
	/Users/me/git/github.com/abdullah-alaadine/local-git-contributions-visualizer/stats.go:25 +0x24
main.main()
	/Users/me/git/github.com/abdullah-alaadine/local-git-contributions-visualizer/main.go:22 +0x134
```

Running on latest MacOS, go version go1.20.5 darwin/arm64

Thanks!
Johan

**Comment by hrtsegv** [comment]
Hi Johan,

Thank you for sharing your work and reporting the issue! I appreciate your contribution. I will take a look at the problem you encountered.

Based on the provided error message, it seems that the issue could be related to an empty Git repository or a lack of access permissions for some repositories. I will investigate further to identify the root cause.

I should enhance the error handling in the code to provide more informative error messages and handle such scenarios gracefully. 

Once I have made the necessary updates, I will notify you and provide an updated version of the tool.

Thank you again for bringing this to my attention!

Best regards,
Abdullah

**Comment by hrtsegv** [comment]
Issue resolved: 
The issue has been addressed and resolved. 
Thank you for bringing this to our attention!
